qlib_init:
  provider_uri: "data/tw_data"
  region: tw
  dataset_cache: "SimpleDatasetCache"
market: &market tw50
benchmark: &benchmark "0050"

data_handler_config: &data_handler_config
  data_loader:
    class: StaticDataLoader
    module_path: qlib.data.dataset.loader
    kwargs:
      config: "./data/precomputed_features/tw50_alpha101_label_1d.parquet"
  start_time: 2014-12-31
  end_time: 2024-12-27

  learn_processors:
    - class: DropnaLabel

  infer_processors:
    - class: ZScoreNorm
      kwargs:
        fields_group: feature
        fit_start_time: 2014-12-31
        fit_end_time: 2021-12-31
    - class: Fillna

port_analysis_config: &port_analysis_config
  strategy:
    class: TopkDropoutStrategy
    module_path: qlib.contrib.strategy
    kwargs:
      signal: <PRED>
      topk: 10
      n_drop: 2
  backtest:
    start_time: 2023-01-01
    end_time: 2024-12-27
    account: 100000000
    benchmark: *benchmark
    exchange_kwargs:
      limit_threshold: 0.1
      deal_price: close
      open_cost: 0.001425
      close_cost: 0.004425
      min_cost: 20

task:
  model:
    class: DNNModelPytorch
    module_path: qlib.contrib.model.pytorch_nn
    kwargs:
      loss: mse
      lr: 1.88e-05
      optimizer: gd
      max_steps: 100
      early_stop_rounds: 10
      batch_size: 1024
      GPU: 0
      weight_decay: 6.679e-06
      pt_model_kwargs:
        input_dim: 56
        act: SiLU

  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: DataHandlerLP
        module_path: qlib.data.dataset.handler
        kwargs: *data_handler_config
      segments:
        train: ["2014-12-31", "2021-12-31"]
        valid: ["2022-01-01", "2022-12-31"]
        test: ["2023-01-01", "2024-12-27"]

  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        model: <MODEL>
        dataset: <DATASET>

    - class: SigAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        ana_long_short: False
        ann_scaler: 252

    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        config: *port_analysis_config

experiment_name: TRAIN_tw50_2LNN_Alpha101
