qlib_init:
  provider_uri: "data/tw_data"
  region: tw

market: &market TW50
benchmark: &benchmark "0050"

data_handler_config: &data_handler_config
  start_time: 2014-12-31
  end_time: 2024-12-27
  fit_start_time: 2014-12-31
  fit_end_time: 2021-12-31
  instruments: *market

  learn_processors:
    - class: DropnaLabel
    - class: CSRankNorm
      kwargs:
        fields_group: label
    - class: Fillna
      kwargs:
        fields_group: feature

  infer_processors:
    - class: RobustZScoreNorm
      kwargs:
        fields_group: feature
        clip_outlier: true
    - class: Fillna
      kwargs:
        fields_group: feature

  label: ["Ref($close, -1)/$close - 1"]

port_analysis_config: &port_analysis_config
  strategy:
    class: TopkDropoutStrategy
    module_path: qlib.contrib.strategy
    kwargs:
      signal: <PRED>
      topk: 10
      n_drop: 2
  backtest:
    start_time: 2023-01-01
    end_time: 2024-12-27
    account: 100000000
    benchmark: *benchmark
    exchange_kwargs:
      limit_threshold: 0.1
      deal_price: close
      open_cost: 0.001425
      close_cost: 0.004425
      min_cost: 20

task:
  model:
    class: TCN
    module_path: qlib.contrib.model.pytorch_tcn_ts
    kwargs:
      d_feat: 158
      num_layers: 3
      n_chans: 24
      kernel_size: 5
      dropout: 0.5
      n_epochs: 100
      lr: 1e-4
      early_stop: 20
      batch_size: 128
      metric: loss
      loss: mse
      optimizer: adam
      n_jobs: 4
      GPU: 0

  dataset:
    class: TSDatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: Alpha158
        module_path: qlib.contrib.data.handler
        kwargs: *data_handler_config
      segments:
        train: ["2014-12-31", "2021-12-31"]
        valid: ["2022-01-01", "2022-12-31"]
        test: ["2023-01-01", "2024-12-27"]
      step_len: 20

  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        model: <MODEL>
        dataset: <DATASET>

    - class: SigAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        ana_long_short: False
        ann_scaler: 252

    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        config: *port_analysis_config

experiment_name: TRAIN_TW50_TCN_Alpha158
